import React, { useEffect, useState } from 'react';
import { useParams, useLocation } from 'react-router-dom';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import GiftCardGenerator from '@/components/GiftCardGenerator';
import { Loader2, ServerCrash } from 'lucide-react';
import { Helmet } from 'react-helmet';

const GiftCardPage = () => {
  const { giftCardId } = useParams();
  const location = useLocation();
  const [cardData, setCardData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    // In a real app, you would fetch data from a backend using giftCardId.
    // For this demo, we'll use the state passed from the previous page.
    if (location.state && location.state.cardData) {
      setCardData(location.state.cardData);
      setLoading(false);
    } else {
      // Simulate an API call if no state is passed
      setTimeout(() => {
        // Mock data for direct navigation
        setCardData({
          amount: 50,
          recipientName: 'Valued Customer (Demo)',
          senderName: 'A Friend',
          message: 'This is a sample gift card generated by direct link access.',
          id: giftCardId,
        });
        setLoading(false);
      }, 1000);
    }
  }, [giftCardId, location.state]);

  return (
    <div className="min-h-screen flex flex-col bg-[#1a2a4a]">
      <Helmet>
        <title>Your Gift Card - Occasions Gifts</title>
        <meta name="description" content="View, manage, and share your generated gift card." />
      </Helmet>
      
      <Header />
      
      <main className="flex-1">
        {loading && (
          <div className="flex flex-col items-center justify-center text-center h-[60vh]">
            <Loader2 className="w-12 h-12 text-[#d4af37] animate-spin mb-4" />
            <h2 className="text-2xl font-bold text-white">Loading Your Gift Card...</h2>
            <p className="text-slate-400">Please wait a moment.</p>
          </div>
        )}
        
        {error && (
           <div className="flex flex-col items-center justify-center text-center h-[60vh]">
            <ServerCrash className="w-12 h-12 text-red-500 mb-4" />
            <h2 className="text-2xl font-bold text-white">Could not load Gift Card</h2>
            <p className="text-slate-400">{error}</p>
          </div>
        )}

        {!loading && !error && cardData && (
          <GiftCardGenerator data={cardData} />
        )}
      </main>
      
      <Footer />
    </div>
  );
};

export default GiftCardPage;